//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DitExplorer.Ntds {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DitExplorer.Ntds.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve the attribute because it does not exist in the database..
        /// </summary>
        internal static string Attribute_NotInDatabase {
            get {
                return ResourceManager.GetString("Attribute_NotInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute cannot be retrieved because the syntax is not supported..
        /// </summary>
        internal static string Attribute_SyntaxNotSupported {
            get {
                return ResourceManager.GetString("Attribute_SyntaxNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the directory.  No root domain was provided, and detection of the root domain failed..
        /// </summary>
        internal static string Directory_NoRootFound {
            get {
                return ResourceManager.GetString("Directory_NoRootFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute cannot be used with this method because it is a single-valued attribute..
        /// </summary>
        internal static string DirectoryObject_AttrIsSingleValued {
            get {
                return ResourceManager.GetString("DirectoryObject_AttrIsSingleValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is disposed and can no longer be used..
        /// </summary>
        internal static string ObjectDisposedMessage {
            get {
                return ResourceManager.GetString("ObjectDisposedMessage", resourceCulture);
            }
        }
    }
}
