//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DitExplorer.UI.WpfApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DitExplorer.UI.WpfApp.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string App_Cancel {
            get {
                return ResourceManager.GetString("App_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIT Explorer encountered an error while opening the DIT file..
        /// </summary>
        public static string App_DitOpenFailed {
            get {
                return ResourceManager.GetString("App_DitOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string App_OK {
            get {
                return ResourceManager.GetString("App_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        public static string ColumnChooser_Title {
            get {
                return ResourceManager.GetString("ColumnChooser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Schema.
        /// </summary>
        public static string DatabaseSchemaViewer_Title {
            get {
                return ResourceManager.GetString("DatabaseSchemaViewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy _DN.
        /// </summary>
        public static string Edit_CopyDnMenuText {
            get {
                return ResourceManager.GetString("Edit_CopyDnMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Selection.
        /// </summary>
        public static string Edit_CopyItemsMenuText {
            get {
                return ResourceManager.GetString("Edit_CopyItemsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Edit_CopyMenuText {
            get {
                return ResourceManager.GetString("Edit_CopyMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy _Value.
        /// </summary>
        public static string Edit_CopyValueMenuText {
            get {
                return ResourceManager.GetString("Edit_CopyValueMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search:.
        /// </summary>
        public static string Edit_SearchLabel {
            get {
                return ResourceManager.GetString("Edit_SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search Now.
        /// </summary>
        public static string Edit_SearchNowAccessText {
            get {
                return ResourceManager.GetString("Edit_SearchNowAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search Subtree....
        /// </summary>
        public static string Edit_SearchSubtreeMenuText {
            get {
                return ResourceManager.GetString("Edit_SearchSubtreeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xport....
        /// </summary>
        public static string File_ExportMenuText {
            get {
                return ResourceManager.GetString("File_ExportMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export Table Data....
        /// </summary>
        public static string File_ExportTableDataMenuText {
            get {
                return ResourceManager.GetString("File_ExportTableDataMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Table Data.
        /// </summary>
        public static string File_ExportTableDataTitle {
            get {
                return ResourceManager.GetString("File_ExportTableDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open DIT File.
        /// </summary>
        public static string File_OpenDitFileTitle {
            get {
                return ResourceManager.GetString("File_OpenDitFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open DIT File....
        /// </summary>
        public static string File_OpenDitMenuText {
            get {
                return ResourceManager.GetString("File_OpenDitMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string General_DescriptionColumnHeader {
            get {
                return ResourceManager.GetString("General_DescriptionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string General_NameAccessText {
            get {
                return ResourceManager.GetString("General_NameAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string General_NameColumnHeader {
            get {
                return ResourceManager.GetString("General_NameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string General_ValueColumnHeader {
            get {
                return ResourceManager.GetString("General_ValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inc_lude subclasses.
        /// </summary>
        public static string IncludeSubclasses_Label {
            get {
                return ResourceManager.GetString("IncludeSubclasses_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainMenu_FileMenuText {
            get {
                return ResourceManager.GetString("MainMenu_FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MainMenu_ViewMenuText {
            get {
                return ResourceManager.GetString("MainMenu_ViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIT Explorer.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member _of.
        /// </summary>
        public static string Object_MemberOfAccessText {
            get {
                return ResourceManager.GetString("Object_MemberOfAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Members.
        /// </summary>
        public static string Object_MembersAccessText {
            get {
                return ResourceManager.GetString("Object_MembersAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Properties.
        /// </summary>
        public static string Object_PropertiesMenuText {
            get {
                return ResourceManager.GetString("Object_PropertiesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Object class:.
        /// </summary>
        public static string ObjectClass_Label {
            get {
                return ResourceManager.GetString("ObjectClass_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Inspector.
        /// </summary>
        public static string ObjectInspector_Title {
            get {
                return ResourceManager.GetString("ObjectInspector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Schema_AttributeColumnHeader {
            get {
                return ResourceManager.GetString("Schema_AttributeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Attributes.
        /// </summary>
        public static string Schema_AttributesAccessText {
            get {
                return ResourceManager.GetString("Schema_AttributesAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string Schema_ColumnsAccessText {
            get {
                return ResourceManager.GetString("Schema_ColumnsAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col. Name.
        /// </summary>
        public static string Schema_DBColumnColumnHeading {
            get {
                return ResourceManager.GetString("Schema_DBColumnColumnHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Indexes.
        /// </summary>
        public static string Schema_IndexesAccessText {
            get {
                return ResourceManager.GetString("Schema_IndexesAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP Name.
        /// </summary>
        public static string Schema_LdapNameColumnHeader {
            get {
                return ResourceManager.GetString("Schema_LdapNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obj. Class.
        /// </summary>
        public static string Schema_ObjClassColumnHeader {
            get {
                return ResourceManager.GetString("Schema_ObjClassColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Schema_ObjectPathColumnHeading {
            get {
                return ResourceManager.GetString("Schema_ObjectPathColumnHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages Used.
        /// </summary>
        public static string Schema_PagesUsedColumnHeader {
            get {
                return ResourceManager.GetString("Schema_PagesUsedColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Schema_RecordCountColumnHeader {
            get {
                return ResourceManager.GetString("Schema_RecordCountColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tables.
        /// </summary>
        public static string Schema_TablesAccessText {
            get {
                return ResourceManager.GetString("Schema_TablesAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Search.
        /// </summary>
        public static string SubtreeSearch_Title {
            get {
                return ResourceManager.GetString("SubtreeSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns....
        /// </summary>
        public static string View_ColumnsMenuText {
            get {
                return ResourceManager.GetString("View_ColumnsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database _Schema.
        /// </summary>
        public static string View_DatabaseSchema {
            get {
                return ResourceManager.GetString("View_DatabaseSchema", resourceCulture);
            }
        }
    }
}
